Repository neerajdembla212/neerajdembla212.github.io, pull requests merged in 2021-07, with the labels that each got.

#13 Navbar updated remaining menu items
  LESS/custom.less
  css/style.css
  help.html
  index.html
  refer-a-friend.html
  settings.html
Labels: Ready for Code Review

#28 Fea/table row strategy provider list view
  LESS/custom.less
  LESS/media.less
  LESS/navigation.less
  css/style.css
  strategy-providers-list.html
Labels: enhancement

#29 updating list component with styles
  LESS/custom.less
  LESS/navigation.less
  css/style.css
  js/strategy-provider.js
  strategy-providers-grid.html
  strategy-providers-list.html
Labels: Ready for Code Review, duplicate

#31 adding dropdown in navbar on extracted menu in all html files
  LESS/navigation.less
  copy-traders.html
  copypip-academy.html
  css/style.css
  help.html
  index.html
  js/inspinia_custom.js
  js/navigation.js
  my-portfolio.html
  news-feed.html
  refer-a-friend.html
  settings.html
  simulation.html
  strategy-providers-grid.html
  strategy-providers-list.html
  trade-terminal.html
  watchlist.html
Labels: Ready for Code Review
